# version: "3.8"

# services:
#   api:
#     build: ./api
#     ports:
#       - "3000:3000"
#     env_file: .env.example
#     depends_on:
#       - rabbitmq

#   # consumer:
#   #   build: ./consumer
#   #   env_file: .env.example
#   #   depends_on:
#   #     - rabbitmq
#   #     - mongo


#   consumer:
#   build: ./consumer
#   command: node worker.js
#   depends_on:
#     - rabbitmq
#     - mongo
#   environment:
#     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
#     DATABASE_URL: mongodb://mongo:27017/activity_db

#   rabbitmq:
#     image: rabbitmq:3-management
#     ports:
#       - "5672:5672"
#       - "15672:15672"

#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"





version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672

  consumer:
    build:
      context: ./consumer
    command: node worker.js
    depends_on:
      - rabbitmq
      - mongo
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: mongodb://mongo:27017/activity_db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
